# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e9e972ccda605be509f283cea0962bb8d12a9aa30ab6e59f52bd82c2e2949dc0503b7489e303b3602317a6f495ab89c5b235024de6ffe3c1d6734f7792a0e84

test:
  secret_key_base: ccc1068bb2c087299edee1a5d478de1eb5e993180d18dd38927af5d2bee73497958caa78ad8a3dc870e0fbfc98f55c3b96053c2679de0dfa6cb3af1ec74e7229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
